[env.production]
name = "fuwari-blog"
compatibility_date = "2024-01-15"

[[env.production.routes]]
pattern = "yourdomain.com/*"
zone_name = "yourdomain.com"

[build]
command = "pnpm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "directory"
dir = "dist"